-- Table: public.user_info
-- DROP TABLE IF EXISTS public.user_info;
CREATE TABLE IF NOT EXISTS public.user_info (
    user_id bigint NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    grade integer,
    class_number integer,
    major character varying(100) COLLATE pg_catalog."default",
    school character varying(100) COLLATE pg_catalog."default",
    role_name jsonb,
    CONSTRAINT "user_id 学号" PRIMARY KEY (user_id)
) TABLESPACE pg_default;
ALTER TABLE IF EXISTS public.user_info OWNER to postgres;
-- Table: public.game
CREATE TABLE IF NOT EXISTS public.game (
    game_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    game_title character varying COLLATE pg_catalog."default" NOT NULL,
    gamers jsonb NOT NULL,
    CONSTRAINT game_pkey PRIMARY KEY (game_id)
) TABLESPACE pg_default;
ALTER TABLE IF EXISTS public.game OWNER to postgres;
-- Table: public.record
CREATE TABLE IF NOT EXISTS public.record (
    game_id bigint NOT NULL,
    gamer_id bigint NOT NULL,
    awards jsonb NOT NULL,
    CONSTRAINT record_pk PRIMARY KEY (game_id, gamer_id)
) TABLESPACE pg_default;
ALTER TABLE IF EXISTS public.record OWNER to postgres;